name: BRANQUINHO
favicon: null
layout_spectrum: 0.50096
typography_spectrum: 0.10771
title: BRANQUINHO - Fine art happiness photographers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffbf8'
    - '#707e65'
    - '#b7b7b5'
    - '#444e57'
    - '#171c1b'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0
  rhythmicContrast: 1
purpose:
  - name: shares
    item: 8ccab3ae-8bd1-4c9c-a929-2dcd27f9c346
    url: null
